# config/schema/commerce_realex.schema.yml
commerce_payment.commerce_payment_gateway.plugin.realex_redirect_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    realex_server_url:
      type: string
      label: 'Server URL'
    realex_merchant_id:
      type: string
      label: 'Merchant ID'
    realex_account:
      type: string
      label: 'Realex Account'
    realex_shared_secret:
      type: string
      label: 'Shared Secret'
